image: gradle:6.7-jdk15

stages:
    - build
    - test
    - staticAnalysis

build:
    stage: build
    script:
        - gradle build

checkStyle:
    stage: staticAnalysis
    script: gradle checkstyleMain checkStyleTest
    allow_failure: true

PMD:
    stage: staticAnalysis
    script: gradle pmdMain pmdTest
    allow_failure: true

test:
    stage: test
    script: gradle test
